"""Fixed Cascade Delete for Continent & Country

Revision ID: af93cfe21e07
Revises: de5e334d0cc4
Create Date: 2021-11-08 10:54:42.924362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af93cfe21e07'
down_revision = 'de5e334d0cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('countries_continent_id_fkey', 'countries', type_='foreignkey')
    op.create_foreign_key(None, 'countries', 'continents', ['continent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'countries', type_='foreignkey')
    op.create_foreign_key('countries_continent_id_fkey', 'countries', 'continents', ['continent_id'], ['id'])
    # ### end Alembic commands ###
